name: Daily Paper du jour

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "== PWD ==" && pwd
          echo "== LS root ==" && ls -la
          echo "== HEAD package.json ==" && head -n 40 package.json || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (no lockfile required)
        run: |
          npm -v && node -v
          npm install --no-audit --no-fund || npm install --legacy-peer-deps --no-audit --no-fund

      - name: Generate daily paper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # optionnel
        run: npm run generate

      - name: Build
        run: |
          npm run build
          echo "== After build =="
          ls -la
          echo "== Dist content =="
          ls -la dist || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path
