name: Daily Paper du jour

on:
  schedule:
    - cron: '0 6 * * *'      # exécution quotidienne
  workflow_dispatch: {}       # bouton "Run workflow"
  push:
    branches: [ main ]        # déclenche aussi sur push

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "== PWD ==" && pwd
          echo "== LS root ==" && ls -la
          echo "== Show package.json (head) ==" && head -n 40 package.json || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # pas de cache pour éviter l'avertissement de lockfile

      - name: Ensure package.json exists
        run: |
          test -f package.json || (echo "❌ package.json i
