name: Daily Article

on:
  schedule:
    - cron: '0 6 * * *'   # tous les jours à 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

# Empêche deux runs d'écrire en même temps
concurrency:
  group: content-writes
  cancel-in-progress: false

jobs:
  write-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Generate daily article
        run: npm run generate:article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}

      - name: Commit & push (with rebase)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No new article"
            exit 0
          fi

          git commit -m "feat(article): $(date -u +%F) - article quotidien"

          # Se remettre à jour puis pousser proprement
          git config pull.rebase true
          git config rebase.autoStash true
          git fetch origin main
          git pull --rebase origin main
          git push
