name: Daily Article

on:
  schedule:
    - cron: '0 6 * * *'   # tous les jours à 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  write-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Generate daily article
        run: npm run generate:article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}

      - name: Commit article
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No new article"
          else
            git commit -m "feat(article): ${date -u +'%Y-%m-%d'} — article quotidien"
            git push
          fi
